#!/bin/bash

if [[ $# -lt 4 ]]; then
  echo "./scripts/generate_flag POLICY WORKLOAD FORK_NUM CALC_NUM"
  exit 1
fi

# enable only one of options
cat << EOF | sed -E "s/($1) 0/\1 1/g; s/($2) 0/\1 1/g"
#define IS_DEBUG 0

#define IS_MULTIPLE_RUNQUEUE 0
#define IS_ROUNDROBIN 0

#define IS_YIELD_REPEAT 0
#define IS_CALCULATION 0
#define IS_LARGEWRITE 0

#define FORK_NUM $3
#define CALC_NUM $4
#define CALC_LOOP 100000000

extern int context_switch_num;
extern int steal_num;
EOF
